refactor: SU, SUTest
sfa-siard/EnterUtilities pull request #7
Opened 2024-06-04 14:47 UTC by llorentelemmc

2024-06-07 07:15 UTC, mburri commented on src/main/java/ch/enterag/utils/cli/Arguments.java
The renaming of the methods confuses me a little bit. I looks like these methods are not used - but in this case, we could also simply delete them? Or make them private or package private.

In any case, the test methods for these methods should be renamed too!

2024-06-07 07:26 UTC, mburri requested changes

2024-06-07 07:26 UTC, mburri commented on src/main/java/ch/enterag/utils/SU.java
I think we should deprecate all methods that now just lookup the charset from the given string and then call `s.getBytes(charset)` and tell the users that they should just use `s.getBytes(charsetName)`

2024-06-10 07:30 UTC, llorentelemmc commented on src/main/java/ch/enterag/utils/cli/Arguments.java
I had renamed them during [refactoring of Arguments](https://github.com/sfa-siard/EnterUtilities/pull/5/files), without checking whether they were still used in other projects. `getOption`, `getArgument`, and `getArguments` are still in use in other projects, so I reverted to the original method name. For example, in this file you can see all three: https://github.com/sfa-siard/Zip64File/blob/main/src/ch/enterag/zip/zip64.java#L220, https://github.com/sfa-siard/Zip64File/blob/main/src/ch/enterag/zip/zip64.java#L222, https://github.com/sfa-siard/Zip64File/blob/main/src/ch/enterag/zip/zip64.java#L281

2024-06-10 08:09 UTC, mburri approved these changes

2024-06-10 08:09 UTC, merged